// Startup scaling test: how long does Muxus take to become usable as the
// host list and the session history grow?
//
//   node hack/startup-scale.mjs                        # 0, 100, 700, 2000 hosts
//   SCALE_SIZES=700,1500 node hack/startup-scale.mjs   # pick the sizes
//   SCALE_RUNS=5 node hack/startup-scale.mjs           # median of 5 per size
//   SCALE_CPU_THROTTLE=4 node hack/startup-scale.mjs   # emulate a slower CPU
//   SCALE_PROFILE=1 node hack/startup-scale.mjs        # keep .cpuprofile files
//   SCALE_TABS=0 node hack/startup-scale.mjs           # no workspace to restore
//
// Build first (`pnpm build`, or at least server + client). Each size gets a
// throwaway HOME under the OS temp dir, so nothing touches your real
// ~/.ssh or the real database:
//
//   - half the hosts are OpenSSH aliases in ~/.ssh/config, half are Muxus-owned
//     saved hosts, spread over two levels of folders (the MobaXterm-import
//     shape), with folder SSH defaults on every customer folder
//   - one recorded session per host in the session history
//   - a known_hosts line per host
//   - a saved workspace of SCALE_TABS (default 6) local terminal tabs, which
//     the app restores and connects at boot like a real session would
//
// Per size it reports the embedded server's cold start (process spawn →
// listening, the part the desktop app blocks its window on), the boot API
// requests, and the renderer: DOMContentLoaded, first host row, all rows,
// every restored tab connected, and main-thread long-task time. The browser
// is headless Chromium on this machine's CPU, so absolute numbers are a lower
// bound for a slower laptop; the trend across sizes is the signal.
import { spawn } from 'node:child_process';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { chromium } from 'playwright-core';

const ROOT = path.resolve(import.meta.dirname, '..');
const SIZES = (process.env.SCALE_SIZES ?? '0,100,700,2000')
  .split(',')
  .map((value) => Number(value.trim()))
  .filter((value) => Number.isInteger(value) && value >= 0);
const RUNS = Math.max(1, Number(process.env.SCALE_RUNS ?? 3));
const CPU_THROTTLE = Math.max(1, Number(process.env.SCALE_CPU_THROTTLE ?? 1));
const PROFILE = process.env.SCALE_PROFILE === '1';
const TABS = Math.max(0, Number(process.env.SCALE_TABS ?? 6));
const HOSTS_PER_FOLDER = 12;
/** TREE_ROW_PITCH in client/src/components/sidebar/tree-row-style.ts: 26px rows, 1px apart. */
const ROW_PITCH = 27;
const CHROME = process.env.CHROME || undefined;
const TOKEN = 'dev';

const serverModule = (relative) => pathToFileURL(path.join(ROOT, 'server/dist', relative)).href;

function median(values) {
  const sorted = [...values].sort((a, b) => a - b);
  return sorted[Math.floor(sorted.length / 2)];
}

function folderFor(index) {
  const folder = Math.floor(index / HOSTS_PER_FOLDER);
  return `Customer ${String(Math.floor(folder / 4) + 1).padStart(3, '0')}/Site ${(folder % 4) + 1}`;
}

/** Seed ~/.ssh, the database and the session history for `count` hosts. */
async function seed(count, home) {
  const ssh = path.join(home, '.ssh');
  const data = path.join(home, '.local', 'share', 'muxus');
  await fs.mkdir(ssh, { recursive: true, mode: 0o700 });
  await fs.mkdir(data, { recursive: true, mode: 0o700 });

  const opensshCount = Math.ceil(count / 2);
  const config = ['# generated by hack/startup-scale.mjs', ''];
  const knownHosts = [];
  for (let i = 0; i < count; i += 1) {
    const address = `10.${Math.floor(i / 65_536) % 256}.${Math.floor(i / 256) % 256}.${i % 256}`;
    knownHosts.push(`${address} ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI${String(i).padStart(43, 'A')}`);
    if (i >= opensshCount) continue;
    config.push(
      `# Imported from MobaXterm: ${folderFor(i)}`,
      `Host node-${String(i).padStart(5, '0')}`,
      `    HostName ${address}`,
      '    User admin',
      ...(i % 5 === 0 ? ['    ProxyJump node-00000'] : []),
      ...(i % 7 === 0 ? [`    LocalForward ${20_000 + i} 127.0.0.1:80`] : []),
      '',
    );
  }
  config.push('Host *', '    ServerAliveInterval 30', '    AddKeysToAgent yes', '');
  await fs.writeFile(path.join(ssh, 'config'), config.join('\n'), { mode: 0o600 });
  await fs.writeFile(path.join(ssh, 'known_hosts'), `${knownHosts.join('\n')}\n`, { mode: 0o600 });

  const { MuxusDatabase } = await import(serverModule('persistence/database.js'));
  const database = new MuxusDatabase(path.join(data, 'muxus.sqlite3'));
  const folders = new Set();
  try {
    for (let i = 0; i < count; i += 1) {
      const group = folderFor(i);
      folders.add(group.split('/')[0]);
      if (i < opensshCount) {
        database.updateOpenSshMetadata(`node-${String(i).padStart(5, '0')}`, {
          group,
          ...(i % 9 === 0 ? { color: '#3b82f6' } : {}),
        });
        continue;
      }
      const saved = database.saveSavedHostProfile({
        name: `saved-${String(i).padStart(5, '0')}`,
        profile: {
          kind: 'ssh',
          target: `10.${Math.floor(i / 256) % 256}.${i % 256}.1`,
          useConfig: false,
          user: 'root',
          port: 22,
        },
      });
      database.updateSavedHostMetadata(saved.id, { group });
    }
    for (const folder of folders) {
      database.upsertFolderSettings(folder, { user: 'ops', identitiesOnly: true });
    }
    if (TABS > 0) {
      // Local tabs connect on restore without any network, and each one walks
      // through the same connecting → connected updates an SSH tab does.
      const tabs = Array.from({ length: TABS }, (_, index) => ({
        id: `scale-tab-${index}`,
        kind: 'terminal',
        title: `Local ${index + 1}`,
        profile: { kind: 'local', shell: '/bin/bash' },
        offerReconnect: false,
      }));
      database.saveWorkspace({
        name: 'Scale test',
        layout: {
          version: 1,
          root: { id: 'scale-pane', type: 'pane', tabs, activeTabId: tabs[0].id },
          activePaneId: 'scale-pane',
        },
        multiExecGroups: [],
      });
    }
  } finally {
    database.close();
  }

  // One finished recording per host: the history worker walks these at boot.
  const { SessionHistoryStore } = await import(serverModule('session-logging/history-store.js'));
  const settingsDb = new MuxusDatabase(path.join(data, 'muxus.sqlite3'));
  const settings = settingsDb.sessionHistorySettings();
  settingsDb.close();
  const history = await SessionHistoryStore.open({ root: path.join(data, 'history'), settings });
  const policy = { maxPartBytes: 5 * 1024 * 1024, maxParts: 10 };
  const started = Date.now() - count * 60_000;
  for (let i = 0; i < count; i += 1) {
    const startedAt = new Date(started + i * 60_000).toISOString();
    const id = history.beginSession(
      {
        profileKey: `ssh:node-${String(i).padStart(5, '0')}`,
        title: `node-${String(i).padStart(5, '0')}`,
        kind: 'ssh',
        host: `10.0.${Math.floor(i / 256) % 256}.${i % 256}`,
        startedAt,
        captureInput: false,
      },
      policy,
    );
    const events = Array.from({ length: 12 }, (_, sequence) => {
      const text = `[admin@node-${i} ~]$ uptime\n 12:${String(sequence).padStart(2, '0')} up 42 days, load average: 0.0${sequence}\n`;
      return {
        sequence: sequence + 1,
        recordedAt: startedAt,
        elapsedMs: sequence * 250,
        direction: 'output',
        raw: Buffer.from(text),
        text,
      };
    });
    history.append(id, events, policy);
    history.finishSession(id, 'completed', new Date(started + i * 60_000 + 30_000).toISOString());
  }
  await history.close();
  return { folders: folders.size };
}

/**
 * Cold-start the embedded server the way the desktop app does (in-process
 * startServer, bundled logger) and report how long the window would wait.
 */
async function startServerProcess(home) {
  const script = `
    const t0 = performance.now();
    const { startServer } = await import(${JSON.stringify(serverModule('server.js'))});
    const t1 = performance.now();
    const server = await startServer({
      port: 0,
      openBrowser: false,
      prettyLogs: false,
      devToken: 'dev',
      databasePath: ${JSON.stringify(path.join(home, '.local', 'share', 'muxus', 'muxus.sqlite3'))},
    });
    const t2 = performance.now();
    console.log('SCALE_READY ' + JSON.stringify({ importMs: t1 - t0, startMs: t2 - t1, url: server.url.replace(/\\/$/, '') }));
  `;
  const env = {
    ...process.env,
    HOME: home,
    USERPROFILE: home,
    XDG_DATA_HOME: path.join(home, '.local', 'share'),
    XDG_CONFIG_HOME: path.join(home, '.config'),
    LOG_LEVEL: 'warn',
    NODE_ENV: 'production',
  };
  delete env.ZDOTDIR;
  delete env.SSH_AUTH_SOCK;
  // A file, not --eval: worker threads inherit execArgv, and the history
  // worker would choke on --input-type.
  const entry = path.join(path.dirname(home), 'server-entry.mjs');
  await fs.writeFile(entry, script);
  const args = [entry];
  if (PROFILE) args.unshift('--cpu-prof', `--cpu-prof-dir=${path.join(home, 'profiles')}`);
  const spawnedAt = performance.now();
  const child = spawn(process.execPath, args, { cwd: ROOT, env, stdio: ['ignore', 'pipe', 'inherit'] });
  return new Promise((resolve, reject) => {
    let buffered = '';
    child.once('exit', (code) => reject(new Error(`server exited early (${code})`)));
    child.stdout.on('data', (chunk) => {
      buffered += chunk;
      const line = buffered.split('\n').find((entry) => entry.startsWith('SCALE_READY '));
      if (!line) return;
      child.removeAllListeners('exit');
      const ready = JSON.parse(line.slice('SCALE_READY '.length));
      resolve({ child, ...ready, processMs: performance.now() - spawnedAt });
    });
  });
}

async function measureRenderer(browser, url, count, runDir) {
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  const page = await context.newPage();
  // The seeded workspace only holds local tabs; nothing is ever dialled.
  if (TABS === 0) {
    await page.route('**/api/workspaces/latest', (route) => route.fulfill({ json: { workspace: null } }));
    await page.route('**/api/workspaces/startup', (route) =>
      route.request().method() === 'GET' ? route.fulfill({ json: { workspace: null } }) : route.continue(),
    );
  }
  await page.addInitScript(() => {
    window.__scale = { longTasks: 0, longest: 0 };
    new PerformanceObserver((list) => {
      for (const entry of list.getEntries()) {
        window.__scale.longTasks += entry.duration;
        window.__scale.longest = Math.max(window.__scale.longest, entry.duration);
      }
    }).observe({ type: 'longtask', buffered: true });
  });
  const cdp = await context.newCDPSession(page);
  await cdp.send('Performance.enable');
  if (CPU_THROTTLE > 1) await cdp.send('Emulation.setCPUThrottlingRate', { rate: CPU_THROTTLE });
  if (PROFILE) {
    await cdp.send('Profiler.enable');
    await cdp.send('Profiler.setSamplingInterval', { interval: 200 });
    await cdp.send('Profiler.start');
  }

  const requests = new Map();
  page.on('request', (request) => {
    const { pathname } = new URL(request.url());
    if (pathname.startsWith('/api/')) requests.set(request, { path: `${request.method()} ${pathname}`, start: performance.now() });
  });
  page.on('requestfinished', (request) => {
    const entry = requests.get(request);
    if (entry) entry.end = performance.now();
  });

  const navigated = performance.now();
  await page.goto(`${url}/?token=${TOKEN}`, { waitUntil: 'domcontentloaded' });
  const domContentLoaded = performance.now() - navigated;
  const rows = page.locator('[role="tree"][aria-label="Hosts"] [role="treeitem"]');
  let firstRow;
  let allRows;
  if (count > 0) {
    await rows.first().waitFor({ timeout: 120_000 });
    firstRow = performance.now() - navigated;
    // Every host plus its folders is a row (folders open by default). Rows
    // have a fixed pitch, so the tree's height counts them whether or not the
    // rows off screen are actually mounted.
    await page.waitForFunction(
      ({ expected, rowPitch }) => {
        const tree = document.querySelector('[role="tree"][aria-label="Hosts"]');
        return !!tree && Math.round((tree.getBoundingClientRect().height + 1) / rowPitch) >= expected;
      },
      { expected: count, rowPitch: ROW_PITCH },
      { timeout: 120_000, polling: 50 },
    );
    allRows = performance.now() - navigated;
  } else {
    // An empty tree is still rendered, just with no height.
    await page.locator('[role="tree"][aria-label="Hosts"]').waitFor({ state: 'attached', timeout: 60_000 });
    firstRow = allRows = performance.now() - navigated;
  }
  let tabsReady;
  if (TABS > 0) {
    // Hidden tabs stay mounted but do not paint, so read the tab strip's status.
    await page.waitForFunction(
      (expected) => document.querySelectorAll('[data-muxus-tab] [aria-label="Connected"]').length >= expected,
      TABS,
      { timeout: 120_000, polling: 50 },
    );
    tabsReady = performance.now() - navigated;
  }
  // Let the boot requests settle so their timings are complete.
  const settleDeadline = performance.now() + 15_000;
  while (performance.now() < settleDeadline) {
    const open = [...requests.values()].some((entry) => entry.end === undefined);
    if (!open) break;
    await page.waitForTimeout(50);
  }
  await page.waitForTimeout(300);
  const renderedRows = await page.evaluate((rowPitch) => {
    const tree = document.querySelector('[role="tree"][aria-label="Hosts"]');
    return {
      rows: tree ? Math.round((tree.getBoundingClientRect().height + 1) / rowPitch) : 0,
      mounted: document.querySelectorAll('[role="tree"][aria-label="Hosts"] [role="treeitem"]').length,
    };
  }, ROW_PITCH);
  const scale = await page.evaluate(() => window.__scale);
  const metrics = Object.fromEntries(
    (await cdp.send('Performance.getMetrics')).metrics.map((metric) => [metric.name, metric.value]),
  );
  if (PROFILE) {
    const { profile } = await cdp.send('Profiler.stop');
    await fs.writeFile(path.join(runDir, `renderer-${count}.cpuprofile`), JSON.stringify(profile));
  }
  await context.close();

  const api = [...requests.values()]
    .filter((entry) => entry.end !== undefined)
    .map((entry) => ({ path: entry.path, ms: entry.end - entry.start, startedAt: entry.start - navigated }));
  return {
    domContentLoaded,
    firstRow,
    allRows,
    tabsReady,
    renderedRows,
    longTasks: scale.longTasks,
    longest: scale.longest,
    scriptMs: (metrics.ScriptDuration ?? 0) * 1000,
    layoutMs: ((metrics.LayoutDuration ?? 0) + (metrics.RecalcStyleDuration ?? 0)) * 1000,
    heapMb: (metrics.JSHeapUsedSize ?? 0) / 1024 / 1024,
    api,
  };
}

const fmt = (value) => (value === undefined ? '-' : `${Math.round(value)}`);

const scratch = await fs.mkdtemp(path.join(os.tmpdir(), 'muxus-startup-scale-'));

// SCALE_SERVE=700: seed once, start the server and keep it up for a manual
// look (or the desktop app's profiler) instead of measuring.
if (process.env.SCALE_SERVE) {
  const count = Number(process.env.SCALE_SERVE);
  const home = path.join(scratch, `hosts-${count}`, 'home');
  await seed(count, home);
  const server = await startServerProcess(home);
  console.log(`${count} hosts, HOME=${home}\nserver ready in ${fmt(server.processMs)} ms: ${server.url}/?token=${TOKEN}`);
  await new Promise((resolve) => process.once('SIGINT', resolve));
  server.child.kill();
  await fs.rm(scratch, { recursive: true, force: true });
  process.exit(0);
}

const browser = await chromium.launch({
  executablePath: CHROME,
  args: ['--no-sandbox', '--disable-background-timer-throttling', '--disable-renderer-backgrounding'],
});
const results = [];
try {
  for (const count of SIZES) {
    const home = path.join(scratch, `hosts-${count}`, 'home');
    const seedStarted = performance.now();
    const seeded = await seed(count, home);
    console.error(`seeded ${count} hosts in ${seeded.folders} customer folders (${Math.round(performance.now() - seedStarted)} ms)`);
    const runs = [];
    for (let run = 0; run < RUNS; run += 1) {
      const server = await startServerProcess(home);
      try {
        const renderer = await measureRenderer(browser, server.url, count, path.dirname(home));
        runs.push({ server, renderer });
      } finally {
        server.child.kill();
        await new Promise((resolve) => server.child.once('exit', resolve));
      }
    }
    const pick = (read) => median(runs.map(read));
    const apiByPath = new Map();
    for (const { renderer } of runs) {
      for (const entry of renderer.api) {
        const list = apiByPath.get(entry.path) ?? [];
        list.push(entry.ms);
        apiByPath.set(entry.path, list);
      }
    }
    const slowest = [...apiByPath.entries()]
      .map(([name, list]) => ({ name, ms: median(list), calls: list.length / runs.length }))
      .sort((a, b) => b.ms - a.ms);
    results.push({
      count,
      serverProcess: pick((run) => run.server.processMs),
      serverStart: pick((run) => run.server.startMs),
      dcl: pick((run) => run.renderer.domContentLoaded),
      firstRow: pick((run) => run.renderer.firstRow),
      allRows: pick((run) => run.renderer.allRows),
      tabsReady: TABS > 0 ? pick((run) => run.renderer.tabsReady) : undefined,
      rows: pick((run) => run.renderer.renderedRows.rows),
      mounted: pick((run) => run.renderer.renderedRows.mounted),
      longTasks: pick((run) => run.renderer.longTasks),
      longest: pick((run) => run.renderer.longest),
      scriptMs: pick((run) => run.renderer.scriptMs),
      layoutMs: pick((run) => run.renderer.layoutMs),
      heapMb: pick((run) => run.renderer.heapMb),
      apiCount: pick((run) => run.renderer.api.length),
      slowest,
    });
    const last = results.at(-1);
    console.error(
      `  server ${fmt(last.serverProcess)} ms (buildApp+listen ${fmt(last.serverStart)} ms), ` +
        `rows ${fmt(last.allRows)} ms, ${TABS} tabs ${fmt(last.tabsReady)} ms, long tasks ${fmt(last.longTasks)} ms`,
    );
  }
} finally {
  await browser.close();
  if (!PROFILE) await fs.rm(scratch, { recursive: true, force: true });
}

console.log(
  `\nStartup scaling (median of ${RUNS} run${RUNS === 1 ? '' : 's'}, ${TABS} restored tab${TABS === 1 ? '' : 's'}${CPU_THROTTLE > 1 ? `, CPU throttled ${CPU_THROTTLE}x` : ''}), all times in ms\n`,
);
console.log(
  ['hosts', 'server', 'buildApp', 'DCL', '1st row', 'all rows', 'tabs', 'rows', 'mounted', 'longtask', 'longest', 'script', 'layout', 'heap MB', 'api reqs']
    .map((title) => title.padStart(9))
    .join(''),
);
for (const row of results) {
  console.log(
    [row.count, row.serverProcess, row.serverStart, row.dcl, row.firstRow, row.allRows, row.tabsReady, row.rows, row.mounted, row.longTasks, row.longest, row.scriptMs, row.layoutMs, row.heapMb, row.apiCount]
      .map((value) => fmt(value).padStart(9))
      .join(''),
  );
}
console.log('\nSlowest boot requests per size:');
for (const row of results) {
  const top = row.slowest
    .slice(0, 5)
    .map((entry) => `${entry.name} ${fmt(entry.ms)}${entry.calls > 1 ? ` ×${entry.calls}` : ''}`)
    .join(', ');
  console.log(`  ${String(row.count).padStart(5)}: ${top}`);
}
if (PROFILE) console.log(`\nProfiles kept under ${scratch}`);
